### ISSUE TITLE
Stop listening

### ISSUE THREAD

**Issue by indigoswann** [jellyfishsolutions/broadcast-bus#1]
hi, it is great package i use in a flutter app like i use in my vue.js app bus.  can provide method for `stopListening` to dismount the bus?

**Comment by Sprechen** [comment]
Hi, the bus returns a standard flutter `Stream`. If you use it in a stream builder, it is automatically disposed. Otherwise, when you use the `listen` method, you receive a `StreamSubscription` object. To "stop listening", you can use its `cancel()` method.

**Comment by indigoswann** [comment]
thank you @Sprechen i appreciate the answer
